/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This schema describes metadata of the Aware Token Metadata Standard
 */
export interface Aware20221012 {
  /**
   * The description of the AwareToken
   */
  description: string;
  /**
   * This property is the name of the Aware Token
   */
  name: string;
  /**
   * This property defines the calendar version of the schema so that consumers can correctly parse the json
   */
  version: string;
  /**
   * This property defines the date of creation in json
   */
  date?: string;
  /**
   * This property defines the Aware Token Type in json
   */
  awareTokenType: string;
  /**
   * This property defines the aware AssetId in json
   */
  awareAssetId: string;
  /**
   * This property defines the productionFacility in json
   */
  productionFacility: string;
  /**
   * This property defines the producer name in json
   */
  producer: string;
  /**
   * This property defines the batch no in json
   */
  batchNo: string;
  /**
   * This property defines the valueChainProcess in json
   */
  valueChainProcess?: unknown[];
  /**
   * This property defines the materialSpecs in json
   */
  materialSpecs?: string;
  /**
   * This property defines the color in json
   */
  color?: string;
  /**
   * This property defines the composition in json
   */
  composition?: string;
  /**
   * This property defines the WeightInKgs in json
   */
  weightInKgs: string;
  /**
   * This property defines the Sustainable Process Claim in json
   */
  sustainableProcessClaim?: unknown[];
  /**
   * This property defines the Wet Processing Claim in json
   */
  wetProcessing?: unknown[];
  tracer?: {
    /**
     * This property is about tracer material Addition
     */
    tracerAdded?: string;
    /**
     * This property is about type of tracer whether aware or custom
     */
    typeofTracer?: string;
    [k: string]: unknown;
  };
  /**
   * This property defines the Self-Validation certificate sustainable material in json
   */
  selfValidationCertificate?: unknown[];
  /**
   * This property defines the Environmental scope certificate in json
   */
  environmentalScopeCertificate?: unknown[];
  /**
   * This property defines the Social compliance certificate in json
   */
  socialComplianceCertificate?: unknown[];
  /**
   * This property defines the Chemical compliance certificate in json
   */
  chemicalComplianceCertificate?: unknown[];
  /**
   * This property defines the previous Token on which it is updated in json
   */
  previousTokenDetail?: unknown[];
}
