"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IERC1155Receiver__factory = exports.IERC1155__factory = exports.ERC1155__factory = exports.extensions = void 0;
const tslib_1 = require("tslib");
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.extensions = tslib_1.__importStar(require("./extensions"));
var ERC1155__factory_1 = require("./ERC1155__factory");
Object.defineProperty(exports, "ERC1155__factory", { enumerable: true, get: function () { return ERC1155__factory_1.ERC1155__factory; } });
var IERC1155__factory_1 = require("./IERC1155__factory");
Object.defineProperty(exports, "IERC1155__factory", { enumerable: true, get: function () { return IERC1155__factory_1.IERC1155__factory; } });
var IERC1155Receiver__factory_1 = require("./IERC1155Receiver__factory");
Object.defineProperty(exports, "IERC1155Receiver__factory", { enumerable: true, get: function () { return IERC1155Receiver__factory_1.IERC1155Receiver__factory; } });
//# sourceMappingURL=index.js.map