"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.erc1155 = void 0;
const tslib_1 = require("tslib");
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.erc1155 = tslib_1.__importStar(require("./ERC1155"));
//# sourceMappingURL=index.js.map