"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AwareToken__factory = exports.interfaces = void 0;
const tslib_1 = require("tslib");
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.interfaces = tslib_1.__importStar(require("./interfaces"));
var AwareToken__factory_1 = require("./AwareToken__factory");
Object.defineProperty(exports, "AwareToken__factory", { enumerable: true, get: function () { return AwareToken__factory_1.AwareToken__factory; } });
//# sourceMappingURL=index.js.map