"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IAwareToken__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IAwareToken__factory_1 = require("./IAwareToken__factory");
Object.defineProperty(exports, "IAwareToken__factory", { enumerable: true, get: function () { return IAwareToken__factory_1.IAwareToken__factory; } });
//# sourceMappingURL=index.js.map